import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';


const Home = () => {
  const [data, setData] = useState(null);
  const [ipServer, setIp] = useState('');

  const apiCall = async () => {
    try {
      const res = await fetch(
        `https://api.app-aws-nicolas-rios.link/users/getusers`,
        {
          method: 'GET',
          headers: {
            'X-RapidAPI-Key': 'your-rapidapi-key',
            'X-RapidAPI-Host': 'famous-quotes4.p.rapidapi.com',
          },
        }
      );
      const { data, ip } = await res.json();
      setData(data);
      setIp(ip);
    } catch (e) {
      console.log(e)
    }
  }

  useEffect(() => {
    apiCall();
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.title}>fisrt App aws</h1>
        <h3>{`IP: ${ipServer}`}</h3>
        <h3>datos BD</h3>
        {data && data.map((item) => (
          <div key={item.id} >
            <h2>{`Dato ${item.id}: ${item.nombre} ${item.apellido} ${item.fecha}`}</h2>
          </div>
        ))}
      </div>
    </div>
  )
}

export default Home;